### ISSUE TITLE
Tobii TX300 Eye-Tracker calibration fails

### ISSUE THREAD

**Issue by mselleki** [hsogo/psychopy_tobii_controller#4]
Hey
My Tobii TX300 eye-tracker is working perfectly fine thanks to your package, but I still have problems to detect everyone's eyes : it works perfectly well with me, but fail to calibrate with others persons.
I plugged the LAN directly to the system unit, and I use DVI cable not VGA. I don't use any USB adapter so I don't think I have a loss of power.

Do you have any ideas where this problem can come from ?
Regards, Ilyass

**Comment by hsogo** [comment]
As the last comment on the following thread says, eye detection fails due to a number of factors.
https://developer.tobii.com/community/forums/topic/eyes-are-not-detected-by-eyetracker/

Following FAQs may be helpful.
https://connect.tobiipro.com/s/article/Creating-good-conditions-for-eye-tracking?language=en_US

- Inform your participants not to have heavy make-up or big eye lashes on
- Avoid participants whose pupils are constantly dilated (e.g. because of medication), or are very small
- Avoid performing recordings on participants with wet eyes
- Exclude participants who have had eye surgery
- Exclude participants with cataract, amblyopia, strabismus, nystagmus and eyelid ptosis

https://connect.tobiipro.com/s/article/Creating-good-conditions-with-eye-tracking-with-screen-based-eye-trackers?language=en_US

- If your participant wears glasses that are damaged or dirty, it can affect the quality of eye tracking
- Avoid recording participants who wear progressive glasses or glasses with more than one power

**Comment by mselleki** [comment]
Thanks !
As we are recording EEG in the same time, we use the eye-tracker in a Faraday cage, where the walls are black. Due to the lack of brightness, the eye-tracker couldn't detect anyone's gaze (except mine :D). Problem fixed adding a bright light in front of the participant's face.

Have a nice day, Ilyass
